# Generated by Django 5.2.4 on 2025-07-28 11:37

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_at',
            field=models.DateTimeField(default=auction.models.default_auction_end_time),
        ),
    ]
