# Generated by Django 5.2.4 on 2025-07-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('FA', 'Fashion'), ('HM', 'Home & Garden'), ('CL', 'Collectibles'), ('SP', 'Sports'), ('BK', 'Books'), ('TG', 'Toys & Games'), ('AR', 'Art'), ('JL', 'Jewelry'), ('AU', 'Automotive'), ('MU', 'Music Instruments'), ('PE', 'Pet Supplies'), ('OF', 'Office Supplies'), ('HE', 'Health & Beauty'), ('RE', 'Real Estate'), ('TR', 'Travel'), ('IN', 'Industrial Equipment'), ('FT', 'Food & Drink'), ('SE', 'Services'), ('OT', 'Other')], default='OT', max_length=100, null=True),
        ),
    ]
