# Generated by Django 5.2.4 on 2025-07-28 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auctionlisting_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(default='random', max_length=100),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
