# Generated by Django 5.2.4 on 2025-07-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('AR', 'Art'), ('AU', 'Automotive'), ('BK', 'Books'), ('CL', 'Collectibles'), ('EL', 'Electronics'), ('FA', 'Fashion'), ('FT', 'Food & Drink'), ('HE', 'Health & Beauty'), ('HM', 'Home & Garden'), ('IN', 'Industrial Equipment'), ('JL', 'Jewelry'), ('MU', 'Music Instruments'), ('OF', 'Office Supplies'), ('PE', 'Pet Supplies'), ('RE', 'Real Estate'), ('SE', 'Services'), ('SP', 'Sports'), ('TG', 'Toys & Games'), ('TR', 'Travel'), ('OT', 'Other')], default='OT', max_length=100, null=True),
        ),
    ]
